### ISSUE TITLE
Too Many Origins not working on a server setting

### ISSUE THREAD

**Issue by ChaosMelodious** [MerchantPug/toomanyorigins#1]
I have all the necessary mods to run the Too many Origins, but we cannot activate the mob effects on a server setting. I'm not sure if there is something in the mod that is preventing it but I thought I would let you know.

**Comment by MerchantPug** [comment]
May I have server logs?

**Comment by MerchantPug** [comment]
Okay, I've replicated this with Rocket Jump (crashes the server) and Draconic Breath (doesn't work).

**Comment by MerchantPug** [comment]
Alright. Both of these abilities have been fixed in 0.1.1.
Status Effects should not have any issues unless compatability problems exist if you meant that.

**Comment by Traveler6078** [comment]
I am currently using the newest version of this mod and still receiving the same problems with my server.
